enableInlineBuilds: true

changesetBaseRefs:
  - HEAD

logFilters:
    # SWC always dumps a bunch of platform warnings
  - level: discard
    pattern: '{@swc/core,@next/swc}*architecture is incompatible with this module'
    # https://github.com/seek-oss/vanilla-extract/issues/379
  - level: discard
    pattern: "@vanilla-extract/next-plugin*doesn't provide webpack"
    # https://github.com/conventional-changelog/commitlint/pull/3008
  - level: discard
    pattern: "@commitlint/load*doesn't provide @types/node"
    # Storybook 6.5 has all kinds of missing peers
  - level: discard
    pattern: '@storybook/*'
    # A few lagging on updating range for React 18
  - level: discard
    pattern: provides react*18

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
