enableInlineBuilds: true

logFilters:
  - level: discard
    pattern: '@next/swc'
  - level: discard
    pattern: "@vanilla-extract/next-plugin*doesn't provide webpack"
  - level: discard
    pattern: "@commitlint/load*doesn't provide @types/node"
  - level: discard
    pattern: eslint-config-airbnb-typescript*doesn't provide eslint

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
