changesetBaseRefs:
  - HEAD

compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: true

logFilters:
  - level: discard
    pattern: "{@swc/core,@next/swc,@node-rs/xxhash}*architecture is incompatible with this module"
  - level: discard
    pattern: "@swc-node/jest*doesn't provide typescript"
  - level: discard
    pattern: "@vanilla-extract/next-plugin*doesn't provide webpack"
  - level: discard
    pattern: "@storybook/*"
  - level: discard
    pattern: provides react*18

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.7.0.cjs
