# yaml-language-server: $schema=https://yarnpkg.com/configuration/yarnrc.json

nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.1.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

logFilters:
  # Silence unsupported platform messages from Next.js (SWC)
  - pattern: '@next/swc'
    level: discard

  # Vanilla Extract Next.js plugin wants webpack...
  # See: https://github.com/seek-oss/vanilla-extract/issues/379
  - pattern: "@vanilla-extract/next-plugin*doesn't provide webpack"
    level: discard

  # Transitive dependencies from @hover/javascript (needs to be fixed in @commitlint/load)
  # See: https://github.com/conventional-changelog/commitlint/pull/3008
  - pattern: "@commitlint/load*doesn't provide @types/node"
    level: discard
  # Transitive dependencies from @hover/javascript (needs to be fixed in eslint-config-airbnb-typescript)
  # https://github.com/iamturns/eslint-config-airbnb-typescript/issues/207
  - pattern: "eslint-config-airbnb-typescript*doesn't provide eslint"
    level: discard
