# yaml-language-server: $schema=https://yarnpkg.com/configuration/yarnrc.json

nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.1.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

logFilters:
  # Silence unsupported platform messages from Next.js (SWC)
  - pattern: '@next/swc'
    level: discard

  # Transitive dependencies from @hover/javascript (needs to be fixed in @commitlint/load)
  # @commitlint/load@npm:16.1.0 doesn't provide @types/node (p4cd06), requested by cosmiconfig-typescript-loader
  # See: https://github.com/conventional-changelog/commitlint/pull/3008
  - pattern: "@commitlint/load*doesn't provide @types/node"
    level: discard
  # Transitive dependencies from @hover/javascript (needs to be fixed in eslint-config-airbnb-typescript)
  # eslint-config-airbnb-typescript@npm:16.1.0 [af607] doesn't provide eslint (p04514), requested by eslint-config-airbnb-base
  # eslint-config-airbnb-typescript@npm:16.1.0 [af607] doesn't provide eslint-plugin-import (p6a000), requested by eslint-config-airbnb-base
  # https://github.com/iamturns/eslint-config-airbnb-typescript/issues/207
  - pattern: "eslint-config-airbnb-typescript*doesn't provide eslint"
    level: discard
