enableInlineBuilds: true

logFilters:
  # Next.js' SWC integration dumps a bunch of platform warnings
  - level: discard
    pattern: '@next/swc'
    # https://github.com/seek-oss/vanilla-extract/issues/379
  - level: discard
    pattern: "@vanilla-extract/next-plugin*doesn't provide webpack"
    # https://github.com/conventional-changelog/commitlint/pull/3008
  - level: discard
    pattern: "@commitlint/load*doesn't provide @types/node"
    # https://github.com/iamturns/eslint-config-airbnb-typescript/pull/275
  - level: discard
    pattern: eslint-config-airbnb-typescript*doesn't provide eslint

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
