app = "jrolfs-emulator"

[build]
build-target = "release"
dockerfile = "applications/emulator/Dockerfile"

[env]
CLIENT_ORIGIN = "https://site-three-lilac.vercel.app/"
LOG_LEVEL = "debug"
NODE_ENV = "production"

[[services]]
internal_port = 3000
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = "80"
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = "443"
