extends:
  - '../../.eslintrc.cjs'
rules:
  react/require-default-props: off
  react/no-unknown-property: off
overrides:
  - files:
      - '.storybook/*.ts'
      - './src/storybook/**/*.ts?(x)'
      - '**/*.stories.tsx'
      - './test/**/*.ts?(x)'
      - './jest.setup.cjs'
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
  - files:
      - '**/*.stories.ts?(x)'
    rules:
      'import/no-default-export': off
      'import/prefer-default-export': error
