extends:
  - '../../.eslintrc.cjs'
rules:
  react/require-default-props: off
overrides:
  - files:
      - '.storybook/*.ts'
      - './src/storybook/**/*.ts?(x)'
      - '**/*.stories.tsx'
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
