# yaml-language-server: $schema=https://json.schemastore.org/eslintrc.json

extends: ../../.eslintrc.cjs
rules:
  '@typescript-eslint/require-await': off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_.*'
