# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Pull Request

on:
  push:
    branches:
      - main
      - next

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/install

      - name: Check types
        run: yarn build:types

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/install

      - name: Run lint
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/install

      - name: Run tests
        run: yarn test
