# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Chromatic

on: push

jobs:
  publish-three:
    name: Publish @jrolfs/three
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/install

      - name: Publish @jrolfs/three to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN__THREE }}
          workingDir: packages/three
