# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - next

jobs:
  dependencies:
    name: Fix Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/fix-dependencies
        with:
          token: ${{ secrets.MANYPKG_TOKEN }}

  compile:
    name: Compile
    needs: dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/install

      - name: Check types
        run: yarn build:types

  lint:
    name: Lint
    needs: dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/install

      - name: Run lint
        run: yarn lint

  test:
    name: Test
    needs: dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/install

      - name: Run tests
        run: yarn test
