# yaml-language-server: $schema=https://json.schemastore.org/eslintrc.json

extends: ../../.eslintrc.cjs
rules:
  react/jsx-sort-props:
    - error
    - reservedFirst: false
  react/no-unknown-property: off
  react/require-default-props: off
ignorePatterns:
  - next-env.d.ts
overrides:
  - files:
      - './src/pages/**/*'
    rules:
      'import/no-default-export': off
      'import/prefer-default-export': error
      no-restricted-exports: off
