# yaml-language-server: $schema=https://json.schemastore.org/eslintrc.json

extends: ../../.eslintrc.cjs
rules:
  react/jsx-sort-props:
    - error
    - reservedFirst: false
  react/react-in-jsx-scope: off
ignorePatterns:
  - next-env.d.ts
overrides:
  - files:
      - './src/pages/**/*'
    rules:
      no-restricted-exports: off
